### PR TITLE
Add pipeline hook

### PR DESCRIPTION
**Pull request by knoguchi**
This PR addresses the issue #119 -- smoke tests broken.  I think it's ok to pass the hook function as an optional keyword argument.  I could add a setter `set_pipeline_hook(self, pipeline_hook)` but I didn't want to introduce another api method.

### CODE REVIEW

**Comment by ttt733** [comment]
I'm pretty sure this is almost correct, but the smoke test harness should be setting it as the `.output` method rather than the hook itself. I'll merge this in and fix it in a separate commit before release; thanks!

**Comment by shlomikushchi** [comment]
I have solved this issue in a different way:
https://github.com/alpacahq/pylivetrader/commit/231516323c90e6e59fe865cf2d2b3654d227e40c
there's no need to add another argument to the alogrithm object
closing this PR

**Comment by shlomikushchi** [comment]
after reconsidering the code flow I am bringing this solution back as explained here:
https://github.com/alpacahq/pylivetrader/commit/66e3a1ac876b836a0ca8f8286767234bca12a865

I will merge it to a local branch and make sure everything works smoothly.

**Comment by shlomikushchi** [comment]
so I had to fix some things. check the relevant PR
https://github.com/alpacahq/pylivetrader/pull/141

**Pull request merged**
